export const BOOKS = [
  'Gênesis',
  'Êxodo',
  'Levítico',
  'Números',
  'Deuteronômio',
  'Josué',
  'Juízes',
  'Rute',
  '1 Samuel',
  '2 Samuel',
  '1 Reis',
  '2 Reis',
  '1 Crônicas',
  '2 Crônicas',
  'Esdras',
  'Neemias',
  'Ester',
  'Jó',
  'Salmos',
  'Provérbios',
  'Eclesiastes',
  'Cânticos',
  'Isaías',
  'Jeremias',
  'Lamentações',
  'Ezequiel',
  'Daniel',
  'Oséias',
  'Joel',
  'Amós',
  'Obadias',
  'Jonas',
  'Miquéias',
  'Naum',
  'Habacuque',
  'Sofonias',
  'Ageu',
  'Zacarias',
  'Malaquias',
  'Mateus',
  'Marcos',
  'Lucas',
  'João',
  'Atos',
  'Romanos',
  '1 Coríntios',
  '2 Coríntios',
  'Gálatas',
  'Efésios',
  'Filipenses',
  'Colossenses',
  '1 Tessalonicenses',
  '2 Tessalonicenses',
  '1 Timóteo',
  '2 Timóteo',
  'Tito',
  'Filemom',
  'Hebreus',
  'Tiago',
  '1 Pedro',
  '2 Pedro',
  '1 João',
  '2 João',
  '3 João',
  'Judas',
  'Apocalipse',
] as const

export const BOOK_ABBREV: Record<string, string> = {
  gn: 'Gênesis',
  ex: 'Êxodo',
  lv: 'Levítico',
  nm: 'Números',
  dt: 'Deuteronômio',
  js: 'Josué',
  jz: 'Juízes',
  rt: 'Rute',
  '1sm': '1 Samuel',
  '2sm': '2 Samuel',
  '1rs': '1 Reis',
  '2rs': '2 Reis',
  '1cr': '1 Crônicas',
  '2cr': '2 Crônicas',
  ed: 'Esdras',
  ne: 'Neemias',
  et: 'Ester',
  jó: 'Jó',
  sl: 'Salmos',
  pv: 'Provérbios',
  ec: 'Eclesiastes',
  ct: 'Cânticos',
  is: 'Isaías',
  jr: 'Jeremias',
  lm: 'Lamentações',
  ez: 'Ezequiel',
  dn: 'Daniel',
  os: 'Oséias',
  jl: 'Joel',
  am: 'Amós',
  ob: 'Obadias',
  jn: 'Jonas',
  mq: 'Miquéias',
  na: 'Naum',
  hc: 'Habacuque',
  sf: 'Sofonias',
  ag: 'Ageu',
  zc: 'Zacarias',
  ml: 'Malaquias',
  mt: 'Mateus',
  mc: 'Marcos',
  lc: 'Lucas',
  jo: 'João',
  atos: 'Atos',
  rm: 'Romanos',
  '1co': '1 Coríntios',
  '2co': '2 Coríntios',
  gl: 'Gálatas',
  ef: 'Efésios',
  fp: 'Filipenses',
  cl: 'Colossenses',
  '1ts': '1 Tessalonicenses',
  '2ts': '2 Tessalonicenses',
  '1tm': '1 Timóteo',
  '2tm': '2 Timóteo',
  tt: 'Tito',
  fm: 'Filemom',
  hb: 'Hebreus',
  tg: 'Tiago',
  '1pe': '1 Pedro',
  '2pe': '2 Pedro',
  '1jo': '1 João',
  '2jo': '2 João',
  '3jo': '3 João',
  jd: 'Judas',
  ap: 'Apocalipse',
}

export const TRANSLATIONS = ['ara', 'acf', 'nvi', 'a21', 'nvt', 'naa', 'kjv', 'web'] as const
export type Translation = (typeof TRANSLATIONS)[number]

export const DEFAULT_TRANSLATION: Translation = 'naa'

export const TRANSLATION_LABELS: Record<string, string> = {
  ara: 'Almeida Revista e Atualizada',
  acf: 'Almeida Corrigida Fiel',
  nvi: 'Nova Versão Internacional',
  a21: 'Almeida Século 21',
  nvt: 'Nova Versão Transformadora',
  naa: 'Nova Almeida Atualizada',
  kjv: 'King James Version',
  web: 'World English Bible',
}

export const TRANSLATION_LABELS_EN: Record<string, string> = {
  ara: 'Revised and Updated Almeida',
  acf: 'Faithful Corrected Almeida',
  nvi: 'New International Version',
  a21: 'Almeida 21st Century',
  nvt: 'New Transforming Version',
  naa: 'New Updated Almeida',
  kjv: 'King James Version',
  web: 'World English Bible',
}

export function getTranslationLabels(locale: string): Record<string, string> {
  return locale === 'en' ? TRANSLATION_LABELS_EN : TRANSLATION_LABELS
}

export const BOOKS_EN = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation',
] as const

export const BOOK_ABBREV_EN: Record<string, string> = {
  gen: 'Genesis',
  ex: 'Exodus',
  lev: 'Leviticus',
  num: 'Numbers',
  deut: 'Deuteronomy',
  josh: 'Joshua',
  judg: 'Judges',
  ruth: 'Ruth',
  '1sam': '1 Samuel',
  '2sam': '2 Samuel',
  '1kgs': '1 Kings',
  '2kgs': '2 Kings',
  '1chr': '1 Chronicles',
  '2chr': '2 Chronicles',
  ezra: 'Ezra',
  neh: 'Nehemiah',
  esth: 'Esther',
  job: 'Job',
  ps: 'Psalms',
  prov: 'Proverbs',
  eccl: 'Ecclesiastes',
  song: 'Song of Solomon',
  isa: 'Isaiah',
  jer: 'Jeremiah',
  lam: 'Lamentations',
  ezek: 'Ezekiel',
  dan: 'Daniel',
  hos: 'Hosea',
  joel: 'Joel',
  amos: 'Amos',
  obad: 'Obadiah',
  jon: 'Jonah',
  mic: 'Micah',
  nah: 'Nahum',
  hab: 'Habakkuk',
  zeph: 'Zephaniah',
  hag: 'Haggai',
  zech: 'Zechariah',
  mal: 'Malachi',
  matt: 'Matthew',
  mark: 'Mark',
  luke: 'Luke',
  john: 'John',
  acts: 'Acts',
  rom: 'Romans',
  '1cor': '1 Corinthians',
  '2cor': '2 Corinthians',
  gal: 'Galatians',
  eph: 'Ephesians',
  phil: 'Philippians',
  col: 'Colossians',
  '1thess': '1 Thessalonians',
  '2thess': '2 Thessalonians',
  '1tim': '1 Timothy',
  '2tim': '2 Timothy',
  titus: 'Titus',
  phlm: 'Philemon',
  heb: 'Hebrews',
  jas: 'James',
  '1pet': '1 Peter',
  '2pet': '2 Peter',
  '1john': '1 John',
  '2john': '2 John',
  '3john': '3 John',
  jude: 'Jude',
  rev: 'Revelation',
}

export function getBooks(locale: string): readonly string[] {
  return locale === 'en' ? BOOKS_EN : BOOKS
}

export function getBookAbbrev(locale: string): Record<string, string> {
  return locale === 'en' ? BOOK_ABBREV_EN : BOOK_ABBREV
}
