name = "verbum-vitae-api"
main = "src/index.ts"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "verbum-vitae"
database_id = "2d0926ac-edbd-429b-94f0-523552514bce"

[placement]
mode = "smart"

[observability]
enabled = true

[env.production]
name = "verbum-vitae-api"
